#+title: Curriculum Vitae
#+options: author:t email:t creator:t toc:t num:nil title:t
#+date: \today
#+author: Arjang Talattof, Ph.D.
#+email: arjang@umich.edu
#+twitter: \_cactuscowboy
#+linkedin: arjang-talattof-a974845a
#+github: arjtala
# Local Variables:
# eval: (bibtex-set-dialect 'biblatex)
# End:

Software engineer, scholar of gastrointestinal motility variation, builder robust & scalable sytems.

US Citizen and UK ILR.


* Experience
** Meta
:PROPERTIES:
:LOCATION: London, UK
:END:
*** Research Engineer (IC6)
:PROPERTIES:
:FROM: <2020-01-27>
:TO: Current
:END:
- Developing the next generation of computation in Reality Labs Research, building the digital interface for the physical world
- Creator and maintainer of geospatial ingestion and indexing of audio-video data from Project Aria (see https://about.meta.com/uk/realitylabs/projectaria/)
- Enabled distributed computing to run large-scale optimization libraries on Meta infrastructure
- Contributed to upgrading company-wide Rust libraries;
- Promotion from IC5 to IC6 (July 2022) and three consecutive ratings of Exceeded Expectations during performance evaluation cycles

** Scape Technologies
:PROPERTIES:
:LOCATION: London, UK
:END:
*** Machine Learning Engineer
:PROPERTIES:
:FROM: <2017-08-01>
:TO:   <2020-01-26>
:END:
- Acquired by Facebook January 2020
- Building core data flow and analysis pipeline for location-based recognition, allowing devices to see and remember
  their surroundings and augment the world around them. Cloud infrastructure allows ordinary mobile devices to enhance
  the world around them by overlaying digital items onto the physical world, both indoors and outdoors, using machine vision
  and artificial intelligence.

** Deloitte Consulting LLP
:PROPERTIES:
:LOCATION: Roslyn, VA, USA
:END:
*** Senior Consultant
:PROPERTIES:
:FROM: <2016-08-15>
:TO: <2017-07-31>
:END:
- Mission Analytics in Business Model and Transformation/Strategy and Operations.
- Supporting senior government executives in the development of the organization's
  strategy and business process; assisting in development, collection, analysis,
  and reporting of data by leverage big data and machine learning technologies; serving as domain
  knowledgeable resource in advising the Deloitte team and client on tools and techniques to improve workflow.

** US Food and Drug Administration
:PROPERTIES:
:LOCATION: Silver Spring, MD, USA
:END:
*** Quantitative Research Fellow
:PROPERTIES:
:FROM: <2015-07-15>
:TO: <2016-08-14>
:END:
- Division of Quantitative Methods and Modeling in the Office of Research and Standards within the Office of Generic Drugs.
- Applying mathematical analysis to physiological/molecular based models for drug absorption, bioavailability, distribution
  and effectiveness. Using large data sets to improve the prediction and regulatory decision making for generic drugs.


* Skills
- *Languages*:  Trilingial English, French, and Persian. Conversational Spanish and Italian.
- *Programming*: C, C++, Python, Rust, SQL
- *Activities*: football, hiking, photography, running

* Projects
- *Large-Scale Structure-from-Motion Pipeline* -- /Python, C++, PyTorch, AWS, PostgreSQL, Redis/
  - Deploying and optimizing large computer vision end-to-end processing pipeline.
  - Developing and optimizing code base to improve runtime and significantly reduce costs.
  - Deep learning-based global image feature extraction and large-scale image retrieval.
  - Custom graph database deployment for geospatial image data used in pipeline to build 3D geometric models.
- *Graph Database Analytics* /Scala, Java, Kafka, Cassandra/NoSQL/
  - Leveraging Cassandra and Spark for large-scale graph networks and analyses including:
    - Building tools to explore and analyze graph data in a distributed system
    - Developing machine learning algorithms and automation of real-time entity resolution (data disambiguation) at scale.
    - Dealing with 10^7 (eventually reaching 10^9) daily transactions utilizing Kafka and Spark Streaming to ingest massive amounts of data through an ETL pipeline.
    - Revenue increase from $1.8M to $6.0M; internal investment by firm ($0.5M) to generalize new capability based on client deliverable (see https://www2.deloitte.com/content/dam/Deloitte/de/Documents/operations/knowledge-graphs-pov.pdf)

* Education
** University of Michigan
:PROPERTIES:
:LOCATION: Ann Arbor, MI, USA
:END:
*** PhD Pharmaceutical Sciences
:PROPERTIES:
:FROM:     <2009-09-01>
:TO:       <2015-05-01>
:END:
- /Mechanistic Analysis and Quantification of Gastrointestinal Motility: Physiological Variability and Plasma Level Implications/
** New York University
:PROPERTIES:
:LOCATION: New York, NY, USA
:END:
*** MSc Computational Biology
:PROPERTIES:
:FROM:     <2007-09-01>
:TO:       <2009-05-01>
:END:
** University of Arizona
:PROPERTIES:
:LOCATION: Tucson, AZ, USA
:END:
*** BSc Mathematics
:PROPERTIES:
:FROM:     <2002-08-01>
:TO:       <2006-06-01>
:END:

#+BIBLIOGRAPHY: refs abbrvnat
